// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GogApi.DotNet")>]
[<assembly: AssemblyProductAttribute("GogApi.DotNet")>]
[<assembly: AssemblyDescriptionAttribute("This project aims at providing an interface to use the (unofficial) GOG API from .NET.")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GogApi.DotNet"
    let [<Literal>] AssemblyProduct = "GogApi.DotNet"
    let [<Literal>] AssemblyDescription = "This project aims at providing an interface to use the (unofficial) GOG API from .NET."
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
