// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("GogApi.Dotnet")>]
[<assembly: AssemblyProductAttribute("GogApi.DotNet")>]
[<assembly: AssemblyDescriptionAttribute("")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "GogApi.Dotnet"
    let [<Literal>] AssemblyProduct = "GogApi.DotNet"
    let [<Literal>] AssemblyDescription = ""
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
