name: Automatical Deployment

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: Deploy library to nuget
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Get the version
        id: get_version
        run: tmp="${GITHUB_REF#refs/tags/v}" && echo ::set-output name=VERSION::${tmp%%\+*}
      - name: Add version and pack
        run: dotnet tool restore && dotnet paket restore && dotnet fake run build.fsx -e VERSION=${{ steps.get_version.outputs.VERSION }} target Pack
      - name: Push to Nuget
        run: dotnet nuget push GogApi.DotNet.${{ steps.get_version.outputs.VERSION }}.nupkg -k ${{ secrets.nugetapikey }} -s "nuget"
