name: Build

on: [push, pull_request]

jobs:
  build:
    name: Test building of library
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [6.0.419]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build library
      run: dotnet run build
    - name: Build docs
      run: dotnet run docs
    - name: Test library
      run: dotnet run test
