name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Test building of library
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build library
      run: dotnet tool restore && dotnet paket restore && dotnet fake build
