name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Test building of library
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.802
    - name: Build library
      shell: pwsh
      run: ./build
