name: Release docs

on:
  push:
    tags:
    - 'v*.*.*'
    - '!v*.*.*-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Build docs
      run: dotnet run docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_public
        publish_branch: gh-pages
        force_orphan: true
